package co.edu.unicauca.mvc.vistas.adminConferencia;

import co.edu.unicauca.mvc.controllers.StorageService;
import co.edu.unicauca.mvc.models.Author;
import co.edu.unicauca.mvc.utilities.CustomTextField;
import co.edu.unicauca.mvc.utilities.Elements;
import co.edu.unicauca.mvc.utilities.FieldConfig;
import co.edu.unicauca.mvc.utilities.Utilities;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Default
 */
public class RegisterAuthorWindow extends RegisterWindow {
    private final StorageService<Author> tempAuthors;
    /**
     * Creates new form RegisterAuthorWindow
     * @param tempAuthors
     */
    public RegisterAuthorWindow(StorageService<Author> tempAuthors) {
        super(new JLabel("Registrar Autor"), createInputFields());
        this.tempAuthors = tempAuthors;
    }
    
    private static LinkedHashMap<String, FieldConfig> createInputFields() {
        LinkedHashMap<String, FieldConfig> inputFields = new LinkedHashMap<>();
        inputFields.put("Nombre:", new FieldConfig(new CustomTextField("Nombre: ")));
        inputFields.put("Apellido:", new FieldConfig(new CustomTextField("Apellido: ")));
        inputFields.put("Mail:", new FieldConfig(new CustomTextField("Mail: ")));
        JComboBox<String> comboBoxTipoAutor = new JComboBox<>(new String[] {"Tipo Asociado", "Tipo Independiente"});
        inputFields.put("Tipo de autor:", new FieldConfig(comboBoxTipoAutor));

        return inputFields;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    @Override
    protected void registerAction() {
        ArrayList<String> values = Elements.extractTextFields(fieldConfigs);
        try{
            FieldConfig comboBoxFieldConfig = fieldConfigs.get("Tipo de autor:");
            JComboBox<String> comboBoxTipoAutor = (JComboBox<String>) comboBoxFieldConfig.getFieldType();
            String typeAuthor = (String) comboBoxTipoAutor.getSelectedItem();
            Author author = new Author(values.get(0),values.get(1), values.get(2), typeAuthor);
            System.out.println("Deberia llamar a update");
            tempAuthors.store(author);
            Utilities.successMessage("Se asoció un nuevo autor a este articulo", "Creación de autores");
            cleanInputs();
        } catch (NumberFormatException ex) {
            Utilities.warningMessage("El id debe ser numérico", "Formato de costo inválido");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
