/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.mvc.vistas.adminConferencia;

import co.edu.unicauca.mvc.controllers.StorageService;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JTextField;
import co.edu.unicauca.mvc.models.Conference;
import co.edu.unicauca.mvc.utilities.Utilities;

/**
 *
 * @author Default
 */
public class RegisterConferenceWindow extends RegisterWindow {
    
    private final StorageService<Conference> objStorageService;

    /**
     * Creates new form VtnListarArticulos
     * @param objStorageService
     */
    public RegisterConferenceWindow (StorageService<Conference> objStorageService) {
        super(new JLabel("Registrar Conferencia"), new String[]{"Nombre:","Fecha inicio:","Fecha fin:","Costo:","Ubicacion","Temas"});
        this.objStorageService = objStorageService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void registerAction() {
        ArrayList<String> values = new ArrayList<>();
        for (JTextField input : inputs) {
            values.add(input.getText());
        }

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date startDate = dateFormat.parse(values.get(1));
            Date endDate = dateFormat.parse(values.get(2));

            if (endDate.before(startDate)) {
                Utilities.warningMessage("La fecha de fin debe ser posterior a la fecha de inicio", "Fecha no válida");
                return;
            }

            float cost = Float.parseFloat(values.get(3));
            Conference conference = new Conference(values.get(0), startDate, endDate, cost, values.get(4),new ArrayList<String>());

            if (objStorageService.store(conference)) {
                Utilities.successMessage("El registro de la conferencia fue exitoso", "Registro exitoso");
            } else {
                Utilities.errorMessage("El registro de la conferencia no se realizó", "Error en el registro");
            }

        } catch (NumberFormatException ex) {
            Utilities.warningMessage("El costo debe ser numérico", "Formato de costo inválido");
        } catch (ParseException ex) {
            Utilities.warningMessage("La fecha debe seguir el formato dd/MM/yyyy", "Formato de fecha inválido");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
