package co.edu.unicauca.mvc.vistas.adminConferencia;

import co.edu.unicauca.mvc.controllers.StorageService;
import co.edu.unicauca.mvc.models.Author;
import co.edu.unicauca.mvc.utilities.FieldConfig;
import co.edu.unicauca.mvc.utilities.Utilities;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Default
 */
public class RegisterAuthorWindow extends RegisterWindow {
    
    private final StorageService<Author> objStorageService;
    /**
     * Creates new form RegisterAuthorWindow
     * @param objStorageService
     */
    public RegisterAuthorWindow(StorageService<Author> objStorageService) {
        super(new JLabel("Registrar Autor"), createInputFields());
        this.objStorageService = objStorageService;
    }
    
    private static LinkedHashMap<String, FieldConfig> createInputFields() {
        LinkedHashMap<String, FieldConfig> inputFields = new LinkedHashMap<>();
        inputFields.put("Nombre:", new FieldConfig(new JTextField(20)));
        inputFields.put("Apellido:", new FieldConfig(new JTextField(20)));
        inputFields.put("Id:", new FieldConfig(new JTextField(10)));
        inputFields.put("Mail:", new FieldConfig(new JTextField(30)));
        return inputFields;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    @Override
    protected void registerAction() {
        ArrayList<String> values = new ArrayList<>();
        fieldConfigs.values().stream()
            .map(FieldConfig::getFieldType)
            .filter(JTextField.class::isInstance)
            .map(JTextField.class::cast)
            .map(JTextField::getText)
            .forEach(values::add);
        
        try{
            float id = Float.parseFloat(values.get(2));
            Author author = new Author(values.get(0),values.get(1), values.get(3), id);

            if (objStorageService.store(author))
                Utilities.successMessage("El registro del autor fue exitoso", "Registro exitoso");
            else
                Utilities.successMessage("El registro del autor no se realizo", "Error en el registro");
        } catch (NumberFormatException ex) {
            Utilities.warningMessage("El id debe ser numérico", "Formato de costo inválido");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
