/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.unicauca.mvc.vistas.adminConferencia;

import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoConferencias;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import co.edu.unicauca.mvc.modelos.Conferencia;

/**
 *
 * @author Default
 */
public class VtnListarConferencias extends VtnListar {

    private final ServicioAlmacenamientoConferencias objServicioAlmacenamiento;

    /**
     * Creates new form VtnListarConferencias
     * @param objServicioAlmacenamiento
     */
    public VtnListarConferencias(ServicioAlmacenamientoConferencias objServicioAlmacenamiento) {
        super("Listado de Conferencias", "Registrar Conferencias", new String[]{"Nombre", "Fecha Inicio", "Fecha Fin", "Costo"});
        this.objServicioAlmacenamiento=objServicioAlmacenamiento;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   @Override
    protected void actualizarAction() {                                                 
        llenarTabla();
    }   
    
    @Override
    protected void registrarAction(){
        VtnRegistrarConferencia objVtnRegistrarConferencia=
        new VtnRegistrarConferencia(this.objServicioAlmacenamiento);
        objVtnRegistrarConferencia.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        objVtnRegistrarConferencia.setVisible(true);       
    }
    
    public void limpiarTabla(){

        DefaultTableModel modelo=(DefaultTableModel) this.table.getModel();
        int filas=this.table.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }        
    }
    
    private void llenarTabla()
    {
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        limpiarTabla();
        ArrayList<Conferencia> listaConferencias= (ArrayList<Conferencia>) this.objServicioAlmacenamiento.listarConferencias();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        
        for (int i = 0; i < listaConferencias.size(); i++) {
            String [] fila= { listaConferencias.get(i).getNombre(), formatter.format(listaConferencias.get(i).getFechaInicio()),formatter.format(listaConferencias.get(i).getFechaFin()),listaConferencias.get(i).getCostoInscripcion()+""};
            model.addRow(fila);
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
