package co.edu.unicauca.mvc.vistas.adminConferencia;

import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import co.edu.unicauca.mvc.modelos.Articulo;

/**
 *
 * @author Default
 */
public class VtnListarArticulos extends VtnListar {
    
    private final ServicioAlmacenamientoArticulos objServicioAlmacenamiento;

    /**
     * Creates new form VtnListarArticulos
     * @param objServicioAlmacenamiento
     */
    public VtnListarArticulos(ServicioAlmacenamientoArticulos objServicioAlmacenamiento) {
        super("Listado de Articulos", "Registrar Articulos", new String[]{"Nombre", "Autores", "Cantidad de autores", "Revista"});
        this.objServicioAlmacenamiento=objServicioAlmacenamiento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void actualizarAction() {                                                 
        llenarTabla();
    }   
    
    @Override
    protected void registrarAction(){
        VtnRegistrarArticulo objVtnRegistrarArticulo=
        new VtnRegistrarArticulo(this.objServicioAlmacenamiento);
        objVtnRegistrarArticulo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        objVtnRegistrarArticulo.setVisible(true);       
    }
    
    public void limpiarTabla(){

        DefaultTableModel modelo=(DefaultTableModel) this.table.getModel();
        int filas=this.table.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }        
    }
    
    private void llenarTabla()
    {
        DefaultTableModel model=(DefaultTableModel) this.table.getModel();
        limpiarTabla();
        ArrayList<Articulo> listaArticulos= (ArrayList<Articulo>) this.objServicioAlmacenamiento.listarArticulos();
       
        for (int i = 0; i < listaArticulos.size(); i++) {
            String [] fila= { listaArticulos.get(i).getNombre(), listaArticulos.get(i).getAutores(),(int) (listaArticulos.get(i).getCantidadAutores())+"",listaArticulos.get(i).getRevista()};
            model.addRow(fila);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
