/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.mvc.vistas.adminConferencia;

import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;
import co.edu.unicauca.mvc.modelos.Articulo;
import co.edu.unicauca.mvc.utilidades.Utilidades;

/**
 *
 * @author Default
 */
public class VtnRegistrarArticulo extends VtnRegistrar {
    
    private final ServicioAlmacenamientoArticulos objServicioAlmacenamiento;
    /**
     * Creates new form VtnRegistrarArticulo
     * @param objServicioAlmacenamiento
     */
    public VtnRegistrarArticulo(ServicioAlmacenamientoArticulos objServicioAlmacenamiento) {
        super(new JLabel("Registrar Articulo"), new String[]{"Nombre:","Autores:","Cantidad de autores:","Revista:"});
        this.objServicioAlmacenamiento = objServicioAlmacenamiento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    protected void registrarAction()
    {
        boolean bandera;
        ArrayList<String> values = new ArrayList<>();
        for(JTextField input : inputs)
        {
            values.add(input.getText());
            System.out.println(input.getText());
        }


        try {

            Articulo objArticulo= new Articulo(values.get(0), values.get(1), Float.parseFloat(values.get(2)), values.get(3));

            bandera=this.objServicioAlmacenamiento.almacenarArticulo(objArticulo);

            if(bandera) 
                Utilidades.mensajeExito( "El registro del articulo fue exitoso","Registro exitoso");
            else
                Utilidades.mensajeError( "El registro del articulo no se realizo","Error en el registro");

        } catch (NumberFormatException ex) {
            Utilidades.mensajeAdvertencia("El costo debe ser numerico","Formato de costo invalido");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
