/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.mvc.vistas.adminConferencia;

import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoOrganizadores;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;
import co.edu.unicauca.mvc.modelos.Organizador;
import co.edu.unicauca.mvc.utilidades.Utilidades;

/**
 *
 * @author Default
 */
public class VtnRegistrarOrganizador extends VtnRegistrar {

    private final ServicioAlmacenamientoOrganizadores objServicioAlmacenamiento;
    /**
     * Creates new form VtnRegistrarOrganizador
     * @param objServicioAlmacenamiento
     */
    public VtnRegistrarOrganizador(ServicioAlmacenamientoOrganizadores objServicioAlmacenamiento) {
        super(new JLabel("Registrar Organizador"), new String[]{"Nombre:","Apellido:","Universidad:"});
        this.objServicioAlmacenamiento = objServicioAlmacenamiento;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void registrarAction()
    {
        boolean bandera;
        ArrayList<String> values = new ArrayList<>();
        for(JTextField input : inputs)
        {
            values.add(input.getText());
            System.out.println(input.getText());
        }

        try {
            Organizador objOrganizador= new Organizador(values.get(0), values.get(1), values.get(2));

            bandera=this.objServicioAlmacenamiento.almacenarOrganizador(objOrganizador);

            if(bandera) 
                Utilidades.mensajeExito( "El registro del organizador fue exitoso","Registro exitoso");
            else
                Utilidades.mensajeError( "El registro del organizador no se realizo","Error en el registro");

        } catch (NumberFormatException ex) {
            Utilidades.mensajeAdvertencia("El costo debe ser numerico","Formato de costo invalido");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
